[workspace]
members = ["mtotp", "mtotp-lib"]
resolver = "2"
default-members = ["mtotp-lib"]

[workspace.package]
version = "0.1.3"
authors = ["niuhuan"]
edition = "2021"
license = "MIT"
repository = "https://github.com/niuhuan/mtotp-rs"
